config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :trending_courses
  mount RailsAdmin::Engine => '/edcognitio_admin', as: 'rails_admin'
  resources :cities
  resources :course_categories
  resources :course_sub_categories
  resources :contact_leads, only: [:create, :destroy]
  post '/rate' => 'rater#create', :as => 'rate'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Browserlog::Engine => '/logs'

  # RailsAdmin.config do |config|
  #   config.authorize_with do
  #     redirect_to main_app.root_path 
  #     # unless current_user.role == User::Role::ADMIN
  #   end
  # end

  get 'blog' => 'posts#index', as: 'blog'
  get 'blog/:id' => 'posts#show', as: 'blog_post'
  get 'contact' => 'pages#contact', as: 'contact_us'
  get 'terms-and-conditions' => 'pages#terms', as: 'terms'
  
  resources :localities
  root 'pages#home'

  resources :pages do
    get :autocomplete_course_sub_category_name, :on => :collection
    get :autocomplete_institute_profile_name, :on => :collection
  end

  get 'complete-profile' => 'pages#complete_profile', as: 'complete_profile'
  put 'complete-profile' => 'pages#omniauth_next_step', as: 'omniauth_next_step'

  devise_for :users, controllers: {registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: "confirmations"}
  resources :institute_profiles, only: [:new, :create, :update]
  get 'institute-profile/edit' => 'institute_profiles#edit', as: 'edit_institute_profile'
  get 'student-profile/edit' => 'student_profiles#edit', as: 'edit_student_profile'

  resources :student_profiles

  resources :staffs, only: [:new, :create, :update]
  get 'edit-staff' => 'staffs#edit_staff', as: 'edit_staff'

  resources :courses, only: [:new, :create, :update]
  get 'edit-courses' => 'courses#edit_courses', as: 'edit_courses'

  resources :testimonials, only: [:new, :create, :update]
  get 'edit-testimonials' => 'testimonials#edit_testimonials', as: 'edit_testimonials'

  resources :pictures, only: [:new, :create, :update]
  get 'edit-pictures' => 'pictures#edit_pictures', as: 'edit_pictures'

  resources :certificates, only: [:new, :create, :update]
  get 'edit-certificates' => 'certificates#edit_certificates', as: 'edit_certificates'

  resources :placements, only: [:new, :create, :update]
  get 'edit-placements' => 'placements#edit_placements', as: 'edit_placements'

  resources :videos, only: [:new, :create, :update]
  get 'edit-videos' => 'videos#edit_videos', as: 'edit_videos'

  resources :contacts, only: [:new, :create, :update]
  get 'edit-contacts' => 'contacts#edit_contacts', as: 'edit_contacts' 

  resources :faqs, only: [:new, :create, :update]
  get 'edit-faqs' => 'faqs#edit_faqs', as: 'edit_faqs'

  get 'edit_course_subcategories' => 'course_sub_categories#edit_subcategories', as: 'edit_subcategories'

  resources :bookings, only: [:create]
  get 'dashboard' => 'institute_profiles#dashboard', as: 'dashboard'
  get 'institute-page' => 'pages#institute_page', as: 'institute_page'
  get '/:city/:locality/:institute_name' => 'pages#institute_page', as: 'individual_institute'
  get 'institutes/search' => 'pages#search', as: 'search'

  get 'all-courses' => 'pages#all_course_sub_categories', as: 'all_courses'
  get 'leads' => 'institute_profiles#contact_leads', as: 'lead' 
  get 'analytics' => 'institute_profiles#analytics', as: 'analytics' 

  get '/:tag' => 'pages#tag', as: 'tag'

  # get 'get-preview-images/:id' => 'pages#preview_edit_institute_images', as: 'preview_images'
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :institute_profile
  attr_accessor :id_institute_profile
  validates_presence_of :name, :designation, :specialization, :experience
  validates_inclusion_of :experience, :in => 1..99
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :find_institute, only: [:new, :edit_staff]
  
  def new
  end

  def create
    @institute_profile = InstituteProfile.find(params[:institute_profile][:id_institute_profile]
      )
    count = 0
    staff_params = params[:institute_profile][:staffs_attributes].values
    staff_params.each do |staff_param|
      @staff = @institute_profile.staffs.new
      @staff.name = staff_param[:name]
      @staff.designation = staff_param[:designation]
      @staff.experience = staff_param[:experience]
      @staff.specialization = staff_param[:specialization]
      if @staff.save
        count += 1
      end
    end
    if count < staff_params.count
      flash.now[:notice] =  "Please fix the following errors (new)"
      render 'new'
    else
      redirect_to institute_page_path(anchor: 'staffs-tab'), notice: "Successfully added Staffs."
    end
  end

  def edit_staff
  end

  def update
    @institute_profile = InstituteProfile.find(params[:institute_profile][:id_institute_profile]
      )
    if @institute_profile.update_attributes(staff_parameters)
      redirect_to institute_page_path(anchor: 'staffs-tab'), notice: "Successfully updated."
    else
      flash.now[:notice] =  "Please fix the following errors (edit)"
      render 'edit_staff'
    end
  end

  private
  def find_institute
    @institute_profile = current_user.institute_profile
  end

  def staff_parameters
    params.require(:institute_profile).permit(:id, staffs_attributes: [:id, :name, :specialization, :experience, :designation, :_destroy])
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<section id="landing">
  <div class="custom-bar top-heading-bar">         
    <div class="container custom-container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <h3><%= fa_icon "asterisk", class: "fa-spin" %> Staffs</h3>
              <!-- <p>Please fill these fields to create your Institute page</p> -->
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= link_to "View Dashboard", dashboard_path(id: current_user.institute_profile.id), class: "btn btn-dashboard pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

<section class="about">
  <div class="container custom-container">
    <div class="about-content">
      <%if current_page?(new_staff_path) %> 
      <% url = staffs_path  %>
      <% method =  "post" %>
      <% else  %>
      <% url = staff_path(id: @institute_profile.id) %>
      <% method =  "put" %>
      <% end %>
      <%= simple_form_for @institute_profile, url: url, method: method do |f| %>
      <div id="staffs">
        <%= f.simple_fields_for :staffs do |s| %>
        <%= render 'staff_fields', f: s %>
        <% end %>
        <div class="links">
          <% if current_page?(new_staff_path) %> 
          <span id = "add-new-staff">
            <% end %>
            <!-- <div class="creat-field"> -->
            <%= link_to_add_association  f, :staffs do %>
            <span class="creat-file"><%= fa_icon "plus-circle" %> Add Staff</span>
            <% end %>
            <!-- </div> -->
            <% if current_page?(new_staff_path) %>
          </span>
          <% end %>
        </div>
      </div>
      <%= f.hidden_field :id_institute_profile, value: "#{@institute_profile.id}" %>
      <div class="buttons-group">
        <div class="col-md-12 col-sm-12 col-xs-12 text-left">
          <%= f.button :submit, "Save", class: "blue-btn pull-right submit-course-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/staffs/_staff_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-6 margin-btn-input">
      <%= f.input :name %>
      <%= f.input :specialization %>
    </div>
    <div class="col-md-6 margin-btn-input">
      <%= f.input :designation %>
      <%= f.input :experience, input_html: {max: 99} %>
    </div>
  </div>
  <%= link_to_remove_association f do %>
  <span class="red-color"><%= fa_icon "trash-o" %> Remove Staff</span> 
  <% end %>
  <hr class="custom-hr">
</div>

app/views/staffs/edit_staff.html.erb
    <%= render 'form' %>

app/views/staffs/new.html.erb
  <%= render 'form' %>