config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :trending_courses
  mount RailsAdmin::Engine => '/edcognitio_admin', as: 'rails_admin'
  resources :cities
  resources :course_categories
  resources :course_sub_categories
  resources :contact_leads, only: [:create, :destroy]
  post '/rate' => 'rater#create', :as => 'rate'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Browserlog::Engine => '/logs'

  # RailsAdmin.config do |config|
  #   config.authorize_with do
  #     redirect_to main_app.root_path 
  #     # unless current_user.role == User::Role::ADMIN
  #   end
  # end

  get 'blog' => 'posts#index', as: 'blog'
  get 'blog/:id' => 'posts#show', as: 'blog_post'
  get 'contact' => 'pages#contact', as: 'contact_us'
  get 'terms-and-conditions' => 'pages#terms', as: 'terms'
  
  resources :localities
  root 'pages#home'

  resources :pages do
    get :autocomplete_course_sub_category_name, :on => :collection
    get :autocomplete_institute_profile_name, :on => :collection
  end

  get 'complete-profile' => 'pages#complete_profile', as: 'complete_profile'
  put 'complete-profile' => 'pages#omniauth_next_step', as: 'omniauth_next_step'

  devise_for :users, controllers: {registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: "confirmations"}
  resources :institute_profiles, only: [:new, :create, :update]
  get 'institute-profile/edit' => 'institute_profiles#edit', as: 'edit_institute_profile'
  get 'student-profile/edit' => 'student_profiles#edit', as: 'edit_student_profile'

  resources :student_profiles

  resources :staffs, only: [:new, :create, :update]
  get 'edit-staff' => 'staffs#edit_staff', as: 'edit_staff'

  resources :courses, only: [:new, :create, :update]
  get 'edit-courses' => 'courses#edit_courses', as: 'edit_courses'

  resources :testimonials, only: [:new, :create, :update]
  get 'edit-testimonials' => 'testimonials#edit_testimonials', as: 'edit_testimonials'

  resources :pictures, only: [:new, :create, :update]
  get 'edit-pictures' => 'pictures#edit_pictures', as: 'edit_pictures'

  resources :certificates, only: [:new, :create, :update]
  get 'edit-certificates' => 'certificates#edit_certificates', as: 'edit_certificates'

  resources :placements, only: [:new, :create, :update]
  get 'edit-placements' => 'placements#edit_placements', as: 'edit_placements'

  resources :videos, only: [:new, :create, :update]
  get 'edit-videos' => 'videos#edit_videos', as: 'edit_videos'

  resources :contacts, only: [:new, :create, :update]
  get 'edit-contacts' => 'contacts#edit_contacts', as: 'edit_contacts' 

  resources :faqs, only: [:new, :create, :update]
  get 'edit-faqs' => 'faqs#edit_faqs', as: 'edit_faqs'

  get 'edit_course_subcategories' => 'course_sub_categories#edit_subcategories', as: 'edit_subcategories'

  resources :bookings, only: [:create]
  get 'dashboard' => 'institute_profiles#dashboard', as: 'dashboard'
  get 'institute-page' => 'pages#institute_page', as: 'institute_page'
  get '/:city/:locality/:institute_name' => 'pages#institute_page', as: 'individual_institute'
  get 'institutes/search' => 'pages#search', as: 'search'

  get 'all-courses' => 'pages#all_course_sub_categories', as: 'all_courses'
  get 'leads' => 'institute_profiles#contact_leads', as: 'lead' 
  get 'analytics' => 'institute_profiles#analytics', as: 'analytics' 

  get '/:tag' => 'pages#tag', as: 'tag'

  # get 'get-preview-images/:id' => 'pages#preview_edit_institute_images', as: 'preview_images'
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :institute_profile
  attr_accessor :id_institute_profile

  validates_presence_of :picture, :title, :description
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :find_institute, only: [:new, :edit_certificates]

  def new
  end

  def create
    @institute_profile = InstituteProfile.find(params[:institute_profile][:id_institute_profile]
      )
    count = 0
    certificate_params = params[:institute_profile][:certificates_attributes].values
    certificate_params.each do |certificate_param|
      @certificate = @institute_profile.certificates.new
      @certificate.title = certificate_param[:title]
      @certificate.description = certificate_param[:description]
      @certificate.picture = certificate_param[:picture]
      if @certificate.save
        count += 1
      end
    end
    if count < certificate_params.count
      flash.now[:notice] =  "Please fix the following errors (new)"
      render 'new'
    else
      redirect_to institute_page_path(anchor: 'certificates-tab'), notice: "Successfully added Certificates."
    end
  end

  def edit_certificates
  end

  def update
    @institute_profile = InstituteProfile.find(params[:institute_profile][:id_institute_profile]
      )
    if @institute_profile.update_attributes(certificate_parameters)
      redirect_to institute_page_path(anchor: 'certificates-tab'), notice: "Successfully updated."
    else
      flash.now[:notice] =  "Please fix the following errors (edit)"
      render 'edit_certificates'
    end
  end

  private
  def find_institute
    @institute_profile = current_user.institute_profile
  end

  def certificate_parameters
    params.require(:institute_profile).permit(:id, certificates_attributes: [:id, :title, :description, :picture, :_destroy])
  end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_certificate_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-4">
      <% if f.object.picture.url %>
      <div class="form-group">
        <%= f.label "Picture" %>
        <%= f.file_field :picture, class: "file", data: {show_remove: false, show_upload: false, initial_caption: "#{f.object.picture.url.split("/").last}",initial_preview: "<img src = %s class= 'img-responsive' width='170' height='130' >" %["#{f.object.picture.url}"]} %>
      </div>
      <% else %>
      <div class="form-group">
        <%= f.label "Picture" %>
        <%= f.file_field :picture, class: "file", data: {show_remove: false, show_upload: false} %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 margin-btn-input">
      <%= f.input :title %>
      <%= f.input :description, input_html: {:rows => 4, maxlength: 200} %>
    </div>
  </div>
  <%= link_to_remove_association f do %>
  <span class="red-color"><%= fa_icon "trash-o" %> Remove Certificate</span> 
  <% end %>
  <hr class="custom-hr">
</div>

app/views/certificates/_form.html.erb
<section id="landing">
  <div class="custom-bar top-heading-bar">         
    <div class="container custom-container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <h3><%= fa_icon "asterisk", class: "fa-spin" %> Certificates</h3>
              <!-- <p>Please fill these fields to create your Institute page</p> -->
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= link_to "View Dashboard", dashboard_path(id: current_user.institute_profile.id), class: "btn btn-dashboard pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>


<section class="about">
  <div class="container custom-container">
    <div class="about-content text-center">

      <%if current_page?(new_certificate_path) %> 
      <% url = certificates_path  %>
      <% method =  "post" %>
      <% else  %>
      <% url = certificate_path(id: @institute_profile.id) %>
      <% method =  "put" %>
      <% end %>
      <div class="row">
        <%= simple_form_for @institute_profile, url: url, method: method do |f| %>
        <div id="certificates">
          <%= f.simple_fields_for :certificates do |s| %>
          <%= render 'certificate_fields', f: s %>
          <% end %>
          <div class="links">
            <% if current_page?(new_certificate_path) %> 
            <span id = "add-new-certificate">
              <% end %>
              <!-- <div class="creat-field"> -->
              <%= link_to_add_association  f, :certificates do %>
              <span class="creat-file"><%= fa_icon "plus-circle" %> Add Certificate</span>
              <% end %>
              <!-- </div> -->
              <% if current_page?(new_certificate_path) %>
            </span>
            <% end %>
          </div>
        </div>
        <%= f.hidden_field :id_institute_profile, value: "#{@institute_profile.id}" %>
      <div class="buttons-group">
        <div class="col-md-12 col-sm-12 col-xs-12 text-left">
          <%= f.button :submit, "Save", class: "blue-btn pull-right submit-course-btn" %>
          <% end %>
      </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/certificates/edit_certificates.html.erb
  <%= render 'form' %>

app/views/certificates/new.html.erb
  <%= render 'form' %>