config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :trending_courses
  mount RailsAdmin::Engine => '/edcognitio_admin', as: 'rails_admin'
  resources :cities
  resources :course_categories
  resources :course_sub_categories
  resources :contact_leads, only: [:create, :destroy]
  post '/rate' => 'rater#create', :as => 'rate'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Browserlog::Engine => '/logs'

  # RailsAdmin.config do |config|
  #   config.authorize_with do
  #     redirect_to main_app.root_path 
  #     # unless current_user.role == User::Role::ADMIN
  #   end
  # end

  get 'blog' => 'posts#index', as: 'blog'
  get 'blog/:id' => 'posts#show', as: 'blog_post'
  get 'contact' => 'pages#contact', as: 'contact_us'
  get 'terms-and-conditions' => 'pages#terms', as: 'terms'
  
  resources :localities
  root 'pages#home'

  resources :pages do
    get :autocomplete_course_sub_category_name, :on => :collection
    get :autocomplete_institute_profile_name, :on => :collection
  end

  get 'complete-profile' => 'pages#complete_profile', as: 'complete_profile'
  put 'complete-profile' => 'pages#omniauth_next_step', as: 'omniauth_next_step'

  devise_for :users, controllers: {registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: "confirmations"}
  resources :institute_profiles, only: [:new, :create, :update]
  get 'institute-profile/edit' => 'institute_profiles#edit', as: 'edit_institute_profile'
  get 'student-profile/edit' => 'student_profiles#edit', as: 'edit_student_profile'

  resources :student_profiles

  resources :staffs, only: [:new, :create, :update]
  get 'edit-staff' => 'staffs#edit_staff', as: 'edit_staff'

  resources :courses, only: [:new, :create, :update]
  get 'edit-courses' => 'courses#edit_courses', as: 'edit_courses'

  resources :testimonials, only: [:new, :create, :update]
  get 'edit-testimonials' => 'testimonials#edit_testimonials', as: 'edit_testimonials'

  resources :pictures, only: [:new, :create, :update]
  get 'edit-pictures' => 'pictures#edit_pictures', as: 'edit_pictures'

  resources :certificates, only: [:new, :create, :update]
  get 'edit-certificates' => 'certificates#edit_certificates', as: 'edit_certificates'

  resources :placements, only: [:new, :create, :update]
  get 'edit-placements' => 'placements#edit_placements', as: 'edit_placements'

  resources :videos, only: [:new, :create, :update]
  get 'edit-videos' => 'videos#edit_videos', as: 'edit_videos'

  resources :contacts, only: [:new, :create, :update]
  get 'edit-contacts' => 'contacts#edit_contacts', as: 'edit_contacts' 

  resources :faqs, only: [:new, :create, :update]
  get 'edit-faqs' => 'faqs#edit_faqs', as: 'edit_faqs'

  get 'edit_course_subcategories' => 'course_sub_categories#edit_subcategories', as: 'edit_subcategories'

  resources :bookings, only: [:create]
  get 'dashboard' => 'institute_profiles#dashboard', as: 'dashboard'
  get 'institute-page' => 'pages#institute_page', as: 'institute_page'
  get '/:city/:locality/:institute_name' => 'pages#institute_page', as: 'individual_institute'
  get 'institutes/search' => 'pages#search', as: 'search'

  get 'all-courses' => 'pages#all_course_sub_categories', as: 'all_courses'
  get 'leads' => 'institute_profiles#contact_leads', as: 'lead' 
  get 'analytics' => 'institute_profiles#analytics', as: 'analytics' 

  get '/:tag' => 'pages#tag', as: 'tag'

  # get 'get-preview-images/:id' => 'pages#preview_edit_institute_images', as: 'preview_images'
end

app/models/institute_profile.rb
class InstituteProfile < ActiveRecord::Base
  mount_uploader :cover_photo, CoverPhotoUploader
  mount_uploader :profile_picture, ProfilePictureUploader
  mount_uploader :brochure, CourseAttachmentUploader

  belongs_to :user

  has_many :staffs, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :testimonials, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :certificates, dependent: :destroy
  has_many :placements, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :faqs, dependent: :destroy
  has_many :contact_leads, dependent: :destroy

  attr_accessor :edit_institute_profile_id

  accepts_nested_attributes_for :staffs, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :testimonials, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pictures, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :certificates, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :placements, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :videos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :faqs, reject_if: :all_blank, allow_destroy: true
end

app/controllers/institute_profiles_controller.rb
class InstituteProfilesController < ApplicationController
  before_action :auth_dashboard, only: [:new, :dashboard, :edit, :update, :contact_leads]

  def new
    @institute_profile = InstituteProfile.new
  end

  def create
    @institute_profile = current_user.create_institute_profile(institute_profile_params)
    if @institute_profile.save
      redirect_to dashboard_path(id: @institute_profile.id ), notice: "Created Profile"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @institute_profile.update_attributes(institute_profile_params)
    redirect_to institute_page_path, notice: "Successfully updated Profile."
  end

  def dashboard
  end

  def contact_leads
    @leads = ContactLead.where(institute_profile_id: @institute_profile).order('created_at DESC')
  end

  def analytics
    id = current_user.institute_profile.id
    a = Ahoy::Event.where(name: id.to_s).where(user_id: nil) | Ahoy::Event.where(name: id.to_s).where.not(user_id: current_user.id)
    b = a.map{|i| i.id}
    if params[:days] == "7"
      views = Ahoy::Event.where(id: b).where('time >= ?', Time.now - 7.days).where('time <= ?', Time.now)
      @visits = views.group_by_day(:time, time_zone: "Chennai",format: "%a, %e")
      @time = "7 days"
      @views = views.count
    elsif params[:days] == "30"
      views = Ahoy::Event.where(id: b).where('time >= ?', Time.now - 30.days).where('time <= ?', Time.now)
      @visits = views.group_by_day(:time, time_zone: "Chennai",format: "%a, %e")
      @time = "30 days"
      @views = views.count
    else
      views = Ahoy::Event.where(id: b).where('time >= ?', Time.now - 24.hours).where('time <= ?', Time.now)
      @visits = views.group_by_hour(:time, time_zone: "Chennai",format: "%H:%M")
      @time = "1 day"
      @views = views.count
    end

    contact_leads = ContactLead.where('created_at > ?', Time.now-30.days).where('created_at < ?', Time.now)
    @contact_leads = contact_leads.group_by_day(:created_at, time_zone: "Chennai",format: "%a, %e")
    @contact_lead_count = contact_leads.count
  end

  private

  def find_profile
    # @institute_profile = InstituteProfile.find(params[:id])
    @institute_profile = current_user.institute_profile

  end

  def institute_profile_params
    params.require(:institute_profile).permit(:name, :established, :cover_photo, :profile_picture, :placement_assistance, :tagline, :courses_available, :students_strength, :placement_rate, :institute_bio, :brochure, staffs_attributes: [:name, :specialization, :experience, :designation])
  end

  def auth_dashboard
    if (current_user && current_user.role == User::Role::INSTITUTE)
      @institute_profile = current_user.institute_profile
    else
      redirect_to root_path
    end
  end

  
end

app/helpers/institute_profiles_helper.rb
module InstituteProfilesHelper
end

app/views/institute_profiles/_form.html.erb
     <section id="landing">
      <div class="custom-bar top-heading-bar">         
        <div class="container custom-container">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <h3><%= fa_icon "asterisk", class: "fa-spin" %> About Us </h3>
                  <% if current_page?(new_institute_profile_path) %>
                  <p>Please fill these basic fields. You will then be redirected to your dashboard where you can fill all the other details.</p>
                  <% else %>
                  <!-- <p>Edit your profile.</p> -->
                  <% end %>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </section>

    <section class="about">

      <div class="container custom-container">

        <div class="about-content">

          <%= simple_form_for @institute_profile, html: { id: "profile_form" } do |f| %>
          <!-- <div class="upload-section"> -->
          <!-- <label>Cover Photo</label> -->
          <!-- <span class="pull-right"><%#= image_tag("image-frame.png") %> 870x300 px</span> -->
          
            <!-- <div class="drag-file">
              Dra-g and drop here
            </div> -->
            <!-- </div> -->
            <!-- <a href="#" class="close-section"><i class="fa fa-times" aria-hidden="true"></i></a> -->

            <div class="row">
              <div class="col-md-12">
                <% if f.object.cover_photo.url %>
                <div class="form-group remove-label-float">
                  <%= f.label "Cover Photo" %>
                  <%= f.file_field :cover_photo, class: "file", data: {initial_preview: "<img src = %s class= 'img-responsive edit-cover-photo-size' >" %["#{f.object.cover_photo.url}"], show_upload: false, initial_caption: "#{f.object.cover_photo.url.split("/").last}"} %>
                </div>
                <% else %>
                <div class="form-group remove-label-float">
                  <%= f.label "Cover Photo" %>
                  <%= f.file_field :cover_photo, class: "file", data: {show_upload: false} %>
                </div>
                <% end %>
              </div>
              <hr>
              <div class="col-md-6 col-sm-6 col-xs-12 width">

                <label>Name of the Institute</label>
                <%= f.input :name, label: false, placeholder: "Name of the Institution" %>

              </div>
              <div class="col-md-6 col-sm-6 col-xs-12 year">  
                <label>Year of Establishment</label>

                <div class="row">
                  <div class="col-md-12 col-md-12 col-xs-12">    
                    <%= f.input :established, start_year: Date.today.year - 40, end_year: Date.today.year, label: false %>

                    <!-- <select>
                      <option>
                        00
                      </option>
                    </select>
                    <select>
                      <option>
                        0000
                      </option>
                    </select> -->

                  </div>  
                </div>  
              </div>  
              <hr>

              <div class="submit-btns">
                <div class="col-md-6 col-sm-6 col-xs-12" id="profile-pic-col">

                  <!-- <a href="#" class="gray-btn">Choose Profile Picture</a> -->
                  <% if f.object.profile_picture.url %>
                  <div class="form-group">
                    <%= f.label "Profile Picture" %>
                    <%= f.file_field :profile_picture, class: "file", data: {initial_preview: "<img src = %s class= 'img-responsive' width='186' height='140'>" %["#{f.object.profile_picture.url}"], show_upload: false, show_remove: false, initial_caption: "#{f.object.profile_picture.url.split("/").last}" } %>
                  </div>
                  <% else %>
                  <div class="form-group">
                    <%= f.label "Profile Picture" %>
                    <%= f.file_field :profile_picture, class: "file", data: {show_upload: false, show_remove: false} %>
                  </div>
                  <% end %>
                  <!-- <span class="pull-left"><%#= image_tag("image-frame.png") %> 870x300 px</span>
                  <a href="#" class="close-section pull-right"><i class="fa fa-times" aria-hidden="true"></i></a> -->

                </div>

                <div class="col-md-6 col-sm-6 col-xs-12" id="brochure-col">

                  <!-- <a href="#" class="gray-btn">Choose Brochure</a> -->
                  <span class="pull-left"><%= image_tag("pdf.png") %></span>
                  <!-- <div class="close fileinput-remove" id="hide-remove">×</div> -->
                  <!-- <a href="#" class="close-section pull-right"><i class="fa fa-times" aria-hidden="true"></i></a> -->
                  <% if f.object.brochure.url %>
                  <div class="close fileinput-remove" id="hide-remove">×</div>
                  <div class="form-group">
                    <%= f.label "Course brochure" %>
                    <div class="hide-when-changed">
                      <div class="file-input">
                        <div class="file-preview">
                          <div class="file-preview-frame">
                            <object class="file-object" data=<%= f.object.brochure.url %> type="application/pdf" width="160px" height="160px" internalinstanceid="80">
                             <param name="movie" value="#{f.object.brochure.url.split("/").last}">
                             <param name="controller" value="true">
                             <param name="allowFullScreen" value="true">
                             <param name="allowScriptAccess" value="always">
                             <param name="autoPlay" value="false">
                             <param name="autoStart" value="false">
                             <param name="quality" value="high">
                             <div class="file-preview-other">
                               <span class="file-icon-4x"><i class="glyphicon glyphicon-file"></i></span>
                             </div>
                           </object>
                           <div class="file-thumbnail-footer">
                            <div class="file-footer-caption"><%= f.object.brochure.url.split("/").last %></div>
                          </div>
                        </div>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                  </div>
                  <div id="hide-caption">
                    <%= f.file_field :brochure, class: "file", data: {show_upload: false, show_remove: false, initial_caption: "#{f.object.brochure.url.split("/").last}", allowed_file_extensions: '["pdf"]'} %>
                  </div>
                </div>
                <% else %>
                <div class="form-group">
                  <%= f.label "Course brochure" %>
                  <%= f.file_field :brochure, class: "file", data: {show_upload: false, show_remove: false} %>
                </div>
                <% end %>
                <!--                 <a href="#" class="close-section pull-right"><i class="fa fa-times" aria-hidden="true"></i></a> -->

              </div>
            </div>
            <hr>

            <div class="col-md-12 width">

             <!-- <label>Tagline</label> -->
             <span class="pull-right">Max 60 Charachters</span>
             <%= f.input :tagline, label: "Tagline", placeholder: "Promoting Outstanding Research and Innovative Training", input_html: {maxlength: 60} %>
             <!-- <input type="text" placeholder="ex:  Promoting Outstanding Research and Innovative Training" /> -->

           </div>
           <hr>

           <div class="col-md-4 width">

             <!-- <label>Courses Available</label> -->
             <%= f.input :courses_available, label: "Courses Available", placeholder: "" %>

           </div>
           <div class="col-md-4 width">

             <!-- <label>Students Strength</label> -->
             <%= f.input :students_strength, label: "Students Strength", placeholder: "" %>

           </div>
           <div class="col-md-4 width">

             <!-- <label>Placement Rate in %</label> -->
             <%= f.input :placement_rate, label: "Placement Rate in %", placeholder: "" %>

           </div>
           <hr>
           <div class="col-md-12">
            <div class="checkbox inline checkbox-success">
             <%= f.check_box :placement_assistance, {id: "placement_assistance_box"} %>
             <label for="placement_assistance_box">Do you offer placement assistance?</label>
           </div>
           
         </div>
         <hr>
         <div class="col-md-12">

          <div class="input-bg">

              <!-- <div class="col-md-6 col-sm-6 col-xs-12 width">

                <input type="text" placeholder="Heading ex: About Us" />

              </div> -->
              <div class="col-md-12 col-sm-12 col-xs-12 width">

                <%= f.input :institute_bio, label: "Institute Bio", placeholder: "What sets you apart from the other institutes, etc.", as: :bootsy, input_html: {rows: 6, maxlength: 1000}, editor_options: { image: false} %>

              </div>

            </div>


          </div>
          <hr>

          <!-- <div class="creat-field">
            <div class="col-md-6 col-sm-6 col-xs-12 text-left">

              <a href="#"><span class="creat-file">Create Field</span> <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">

              <span class="pull-right">Max 3 fields can be created</span>

            </div>
          </div>
          <hr> -->
          <div class="buttons-group">

            <div class="col-md-12 col-sm-12 col-xs-12 text-left">
              <%= f.submit "Save", class: "blue-btn pull-right" %>
              <% end %>
              <!-- <a href="#" class="blue-btn">Save</a> -->
              <!-- <a href="#" class="gray-btn">Cancel</a> -->
            </div>

              <!-- <div class="col-md-6 col-sm-6 col-xs-12 text-right">
                <a href="#" class="light-blue-btn">Cancel</a>
              </div> -->

            </div>

          </div>

        </div>  

      </section>

app/views/institute_profiles/analytics.html.erb
<div class="container custom-container">
  <div class="row text-center analytics-row">
    <h3><span style="color: #e74c3c"><%= @views %></span> page views in the last <%= @time %></h3>
    <div class="btn-group">
    <%= link_to "1 day", analytics_path, class: "btn btn-default #{'active' unless params[:days]}" %>
    <%= link_to "7 days", analytics_path(days: 7), class: "btn btn-default #{'active' if params[:days] == '7'}" %>
    <%= link_to "30 days", analytics_path(days: 30), class: "btn btn-default #{'active' if params[:days] == '30'}" %>
      
    </div>
    <%= line_chart @visits.count, discrete: true, xtitle: "Days", ytitle: "Number of page views", library: {yAxis: {allowDecimals: false }}%>

    <hr>
    <hr>
    <h3><span style="color: #e74c3c"><%= @contact_lead_count %></span> leads in the past 30 days</h3>
     <%= column_chart @contact_leads.count, discrete: true, xtitle: "Days", ytitle: "Number of Leads", library: {yAxis: {allowDecimals: false }}%>
  </div>
</div>

app/views/institute_profiles/contact_leads.html.erb
 <div class="row tab-content-row">
   <h3 class="text-center">Contact form Leads</h3>
   <div class="container custom-container">
     <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="text-center">Date</th>
          <th class="text-center">Name</th>
          <th class="text-center">Email</th>
          <th class="text-center">Subject</th>
          <th class="text-center">Message</th>
        </tr>
      </thead>
      <tbody>
        <% @leads.each do |lead| %>
        <tr class="text-center">
          <td><%= lead.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= lead.name %></td>
          <td><%= lead.email %></td>
          <td><%= lead.subject %></td>
          <td><%= lead.message %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/institute_profiles/dashboard.html.erb
<section id="landing">
  <div class="custom-bar top-heading-bar">         
    <div class="container custom-container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <h3>Dashboard</h3>
              <p>Please fill these forms to create your Institute page</p>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= link_to "Institute Page", institute_page_path, class: "btn btn-dashboard pull-right"  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
</section>
<section class="dashboard">
 <div class="container custom-container">
  <div class="row">
   <ul>
    <li class="col-md-2 col-sm-4 col-xs-12">
      <%= link_to(edit_institute_profile_path, class: "active") do %>
      <span><%= image_tag("about-us-dash.png") %></span>
      <span class="hover"><%= image_tag("Dashboard_03.png") %></span>
      <p>About Us</p>
      <% end %>
    </li>
    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.courses.any? %>
      <%= link_to(edit_courses_path) do %>
      <span>
        <%= image_tag('Dashboard_05.png') %>
      </span>
      <span class="hover">
        <%= image_tag('course-info.png') %>
      </span>
      <p>Courses</p>
      <% end %>
      <% else %>
      <%= link_to(new_course_path) do %>
      <span>
        <%= image_tag('Dashboard_05.png') %>
      </span>
      <span class="hover">
        <%= image_tag('course-info.png') %>
      </span>
      <p>Courses</p>
      <% end %>
      <% end %>
    </li>

    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.placements.any? %>
      <%= link_to(edit_placements_path) do %>
      <span>
        <%= image_tag('Dashboard_07.png') %>
      </span>
      <span class="hover">
        <%= image_tag('placement.png') %>
      </span>
      <p>Placements</p>
      <% end %>
      <% else %>
      <%= link_to(new_placement_path) do %>
      <span>
        <%= image_tag('Dashboard_07.png') %>
      </span>
      <span class="hover">
        <%= image_tag('placement.png') %>
      </span>
      <p>Placements</p>
      <% end %>
      <% end %>
    </li>

    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.certificates.any? %>
      <%= link_to(edit_certificates_path) do %>
      <span>
        <%= image_tag('Dashboard_09.png') %>
      </span>
      <span class="hover">
        <%= image_tag('certificates-hover.png') %>
      </span>
      <p>Certificates</p>
      <% end %>
      <% else %>
      <%= link_to(new_certificate_path) do %>
      <span>
        <%= image_tag('Dashboard_09.png') %>
      </span>
      <span class="hover">
        <%= image_tag('certificates-hover.png') %>
      </span>
      <p>Certificates</p>
      <% end %>
      <% end %>
    </li>


    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.staffs.any? %>
      <%= link_to(edit_staff_path) do %>
      <span>
        <%= image_tag('Dashboard_14.png') %>
      </span>
      <span class="hover">
        <%= image_tag('staffs-hover.png') %>
      </span>
      <p>Staffs</p>
      <% end %>
      <% else %>
      <%= link_to(new_staff_path) do %>
      <span>
        <%= image_tag('Dashboard_14.png') %>
      </span>
      <span class="hover">
        <%= image_tag('staffs-hover.png') %>
      </span>
      <p>Staffs</p> 
      <% end %>
      <% end %>

    </li>


    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.pictures.any? %>
      <%= link_to(edit_pictures_path) do %>
      <span>
        <%= image_tag('adasda.png') %>
      </span>
      <span class="hover">
        <%= image_tag('gallery-hover.png') %>
      </span>
      <p>Pictures</p>
      <% end %>
      <% else %>
      <%= link_to(new_picture_path) do %>
      <span>
        <%= image_tag('adasda.png') %>
      </span>
      <span class="hover">
        <%= image_tag('gallery-hover.png') %>
      </span>
      <p>Pictures</p>
      <% end %>

      <% end %>

    </li>


    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.videos.any? %>
      <%= link_to(edit_videos_path) do %>
      <span>
        <%= image_tag('Dashboard_23.png') %>
      </span>
      <span class="hover">
        <%= image_tag('videos.png') %>
      </span>
      <p>Videos</p>
      <% end %>
      <% else %>
      <%= link_to(new_video_path) do %>
      <span>
        <%= image_tag('Dashboard_23.png') %>
      </span>
      <span class="hover">
        <%= image_tag('videos.png') %>
      </span>
      <p>Videos</p>
      <% end %>
      <% end %>
    </li>

    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.testimonials.any? %>
      <%= link_to(edit_testimonials_path) do %>
      <span>
        <%= image_tag('Dashboard_25.png') %>
      </span>
      <span class="hover">
        <%= image_tag('testimonials-hover.png') %>
      </span>
      Testimonials
      <% end %>
      <% else %>
      <%= link_to(new_testimonial_path) do  %>
      <span>
        <%= image_tag('Dashboard_25.png') %>
      </span>
      <span class="hover">
        <%= image_tag('testimonials-hover.png') %>
      </span>
      <p>Testimonials</p>
      <% end %>
      <% end %>

    </li>


    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.faqs.any? %>
      <%= link_to(edit_faqs_path) do %>
      <span>
        <%= image_tag('Dashboard_27.png') %>
      </span>
      <span class="hover">
        <%= image_tag('articles-hover.png') %>
      </span>
      <p>FAQs</p>
      <% end %>
      <% else %>
      <%= link_to(new_faq_path) do %>
      <span>
        <%= image_tag('Dashboard_27.png') %>
      </span>
      <span class="hover">
        <%= image_tag('articles-hover.png') %>
      </span>
      <p>FAQs</p>
      <% end %>
      <% end %>
    </li>


    <li class="col-md-2 col-sm-4 col-xs-12">
      <% if current_user.institute_profile.contacts.any? %>
      <%= link_to(edit_contacts_path) do %>
      <span>
        <%= image_tag('Dashboard_29.png') %>
      </span>
      <span class="hover">
        <%= image_tag('contact-hover.png') %>
      </span>
      <p>Contact Us</p>
      <% end %>
      <% else %>
      <%= link_to(new_contact_path) do %>
      <span>
        <%= image_tag('Dashboard_29.png') %>
      </span>
      <span class="hover">
        <%= image_tag('contact-hover.png') %>
      </span>
      <p>Contact Us</p>
      <% end %>
      <% end %>
    </li> 

    <li class="col-md-2 col-sm-4 col-xs-12">
      <%= link_to(lead_path, class: "call-tracking") do %>
      <span>
        <%= image_tag('call-tracking.png') %>
      </span>
      <span class="hover">
        <%= image_tag('call-tracking.png') %>
      </span>
      Lead Tracking
      <% end %>
    </li>  
    <li class="col-md-2 col-sm-4 col-xs-12">
      <%= link_to(analytics_path, class: "analytics") do %>
        <span>
          <%= image_tag('Dashboard_03_07.png') %>
        </span>
        <span class="hover">
          <%= image_tag('Dashboard_03_07.png') %>
        </span>
        Analytics
      <% end %>
    </li> 
  </ul>
</div>

</div>

</section>

app/views/institute_profiles/edit.html.erb
  <%= render 'form' %>

app/views/institute_profiles/new.html.erb
  <%= render 'form' %>
  